[package]
name = "x11_man"
version = "0.0.2"
edition = "2021"
author = "konkitoman"

[lib]
name = "x11_man"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]